import { Inter } from 'next/font/google';
import '@/styles/globals.css';
import Head from 'next/head';
import NavBar from '@/components/NavBar';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Advanced Animations',
	description: 'Generated by CSS and Javascript'
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className} suppressHydrationWarning={true}>
				<Head>
					<meta name='viewport' content='width=device-width, initial-scale=1' />
					<link rel='icon' href='/favicon.ico' />
				</Head>
				<NavBar />
				<main className='mt-20'>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
